import { Link } from 'react-router-dom'
const ecosystemLinks = [
  { name: 'CoinByte CLI', url: 'https://coinbyte-cli.vercel.app/', badge: 'Testnet' },
  { name: 'Byte AI', url: 'https://v0-byte-e2.vercel.app/', badge: 'Preview' },
  { name: 'Identity Forge Wallet', url: 'https://identity-forge-wallet.vercel.app/', badge: 'Beta' },
  { name: 'AlgoByte', url: 'https://algobyte.vercel.app', badge: 'New' },
  { name: 'Byte Explorer', url: 'https://byte-explorer.vercel.app/', badge: 'New' },
  { name: 'ClawByte', url: 'https://claw-cast.vercel.app/', badge: 'New' },
]
export default function Footer(){return <footer className='border-t border-[var(--border-color)] mt-0'><div className='container mx-auto px-4 max-w-6xl pt-16 pb-8'><div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-10 mb-12'><div className='lg:col-span-2'><div className='flex items-center gap-2 mb-4'><img src='/assets/github-logo.png' alt='CoinByte' className='h-8 w-8'/><span className='text-lg font-bold gradient-text'>CoinByte</span></div><p className='text-sm text-[var(--text-muted)] max-w-xs leading-relaxed mb-4'>Open monetary infrastructure for stable value transfer.</p></div><div><h5 className='font-semibold text-sm mb-4 text-[var(--text-primary)]'>Ecosystem</h5><ul className='space-y-2.5'>{ecosystemLinks.map(l=><li key={l.name}><a href={l.url} target='_blank' rel='noreferrer' className='text-sm text-[var(--text-muted)] hover:text-primary-orange transition-colors flex items-center gap-2'>{l.name}<span className='text-xs px-1.5 py-0.5 rounded bg-primary-orange/10 text-primary-orange'>{l.badge}</span></a></li>)}</ul></div><div><h5 className='font-semibold text-sm mb-4 text-[var(--text-primary)]'>Legal</h5><ul className='space-y-2.5 text-sm text-[var(--text-muted)]'><li><Link to='/privacy'>Privacy Policy</Link></li><li><Link to='/terms'>Terms of Service</Link></li></ul></div></div><div className='flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-[var(--text-muted)]'><p>© 2026 CoinByte Labs, Inc. • Pre-launch testnet phase</p></div></div></footer>}
